// types/database.ts
// This file can hold TypeScript types that match your Supabase tables.
// For now we define light-weight interfaces by hand so you can
// use them throughout the app. You can later replace this with
// types generated by Supabase if you prefer.

// Basic shape of the `profiles` table.
export interface Profile {
  id: string;
  name?: string | null; // User's display name
  age: number | null;
  height: number | null; // in cm
  weight: number | null; // in kg
  goal: "muscle_gain" | "fat_loss" | "maintenance" | null;
  experience_level: "beginner" | "intermediate" | "advanced" | null;
  // gender is stored as a simple string; we use a narrow union in code
  // but allow null when not set.
  gender?: "male" | "female" | "other" | null;
  // activity_level: TEXT column, nullable
  activity_level?: "sedentary" | "light" | "moderate" | "active" | null;
  // workout_streak: INT DEFAULT 0, so it always has a value (never null)
  workout_streak: number;
  // last_workout_date: DATE column, nullable
  // NOTE: This is automatically updated by the streak tracking system.
  // Users should NOT manually edit this field.
  last_workout_date?: string | null; // DATE (YYYY-MM-DD)
  created_at?: string;
}

// Basic shape of the `workout_logs` table.
export interface WorkoutLog {
  id: string;
  user_id: string;
  exercise: string;
  sets: number;
  reps: number;
  weight: number;
  workout_date: string; // DATE (YYYY-MM-DD)
  created_at: string;
}

// Basic shape of the `nutrition_logs` table.
// This version matches the improved schema that supports MyFitnessPal-style logging.
export interface NutritionLog {
  id: string;
  user_id: string;
  food_name: string;
  quantity: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  log_date: string; // stored as a DATE in Supabase (YYYY-MM-DD)
  created_at: string;
}

// Basic shape of the `exercise_progress` table.
// This table stores progressive overload metrics per exercise:
// best_weight: heaviest weight lifted
// best_reps: most reps done
// estimated_1rm: best estimated one-rep max
export interface ExerciseProgress {
  id: string;
  user_id: string;
  exercise_name: string;
  best_weight: number;
  best_reps: number;
  estimated_1rm: number;
  last_updated: string;
}

// Basic shape of the `workout_plans` table.
export interface WorkoutPlan {
  id: string;
  user_id: string;
  plan_json?: any | null; // JSONB column for structured workout plans
  created_at: string;
}


// Basic shape of the `body_weight_logs` table.
export interface BodyWeightLog {
  id: string;
  user_id: string;
  weight: number;
  log_date: string; // DATE (YYYY-MM-DD)
  created_at: string;
}

// Basic shape of the `favorite_foods` table.
export interface FavoriteFood {
  id: string;
  user_id: string;
  food_name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  created_at: string;
}





